<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => '',
    'Access denied.' => '',
    'Access to content management' => '',
    'Add' => '',
    'Answer' => '',
    'Are you sure you want to delete this item?' => '',
    'Backend' => '',
    'Comments' => '',
    'Credentials' => '',
    'Delete' => '',
    'Events' => '',
    'Gear' => '',
    'If you forgot your password you can' => '',
    'Login' => '',
    'Name' => '',
    'Only ajax request suitable.' => '',
    'Part of the title can be selected by [] as a link of the post, in Russian / English' => '',
    'Posts' => '',
    'Reply' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Resume' => '',
    'Root' => '',
    'Rubrics' => '',
    'Save' => '',
    'Select' => '',
    'Signup' => '',
    'Slug' => '',
    'Slug may consists a-z, numbers and minus only.' => '',
    'Submit' => '',
    'Tags' => '',
    'The requested model does not exist.' => '',
    'This page is for registered users. If it\'s not about you, you can go through a simple ' => '',
    'To signup' => '',
    'Update' => '',
    'Users' => '',
    'View' => '',
    'in Russian / English' => '',
    'registration' => '',
    'reset it' => '',
    'wrote' => '',
    'Node can not be deleted!' => '@@@@',
    'Node has not parent!' => '@@@@',
];
