<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Добавить',
    'Consent to the processing of sent data' => '',
    'Content' => 'Содержание',
    'Created' => '',
    'Frequency' => '',
    'Location' => '',
    'Model' => '',
    'Name' => '',
    'Node can not be deleted.' => '',
    'Node has not parent.' => '',
    'Parent' => '',
    'Parent node' => '',
    'Please confirm that you agree to the processing of data sent by you.' => '',
    'Position' => '',
    'Posts' => '',
    'Root' => '',
    'Save' => '',
    'Show' => '',
    'Status' => '',
    'Thread' => '',
    'Verification Code' => '',
    'Visible' => '',
    'hours ago' => '',
    'one hour ago' => '',
    'yesterday' => '',
];
