<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied.' => 'Доступ запрещен.',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот елемент?',
    'Author' => 'Автор',
    'Authors' => 'Авторы',
    'Backend' => 'Админ-панель',
    'Blog' => 'Блог',
    'Cancel' => 'Отмена',
    'Comments' => 'Комментарии',
    'Consent to the processing of sent data' => 'Согласие на обработку отправленных данных',
    'Created at' => 'Добавлен(а)',
    'Credentials' => 'Полномочия',
    'Delete' => 'Удалить',
    'Events' => 'События',
    'Excerpt' => 'Отрывок',
    'Frequency' => 'Частота',
    'Gear' => 'Настройки',
    'Location' => 'Расположение',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Model' => 'Модель',
    'Moderator' => 'Модератор',
    'Modified' => 'Изменено',
    'Name' => 'Имя',
    'Only ajax request suitable.' => 'Нужен только ajax запрос.',
    'Parent' => 'Родитель',
    'Parent node' => 'Родительский узел',
    'Part of the title can be selected by [] as a link of the post' => 'Часть заголовка может быть выбелена [] как ссылка на пост',
    'Please confirm that you agree to the processing of data sent by you.' => 
        'Пожалуйста, подтвердите, что вы согласны на обработку данных, отправленных вами.',
    'Position' => 'Позиция',
    'Posts' => 'Статьи',
    'Previous post' => 'Предыдущий пост',
    'Profile' => 'Профиль',
    'Reply' => 'Ответ',
    'Resume' => 'Заключение',
    'Root' => 'Корень',
    'Rubric' => 'Рубрика',
    'Rubrics' => 'Рубрики',
    'Save' => 'Сохранить',
    'Select' => 'Выбрать',
    'Show' => 'Показывать',
    'Slug' => 'Слаг',
    'Slug may consists a-z, numbers and minus only.' => 'Сдаг может содержать символы a-z, числа и знак минус.',
    'Status' => 'Статус',
    'Sub Title' => 'ПодЗаголовок',
    'Submit' => 'Отправить',
    'Tags' => 'Метки',
    'Tags may consists alphabets, numbers and space only.' => 'Метки монут состоять из буквб цифр и пробела.',
    'The requested model does not exist.' => 'Запрошенная модель не существует.',
    'There are no comments yet.' => 'Комментариев еще нет.',
    'This article is already selected as the previous one.' => 'Данная статья уже выбрана, как предыдущая.',
    'Thumb' => 'Фото',
    'Thread' => 'Нитка',
    'Title' => 'Заголовок',
    'Update' => 'Изменить',
    'Users' => 'Пользователи',
    'Verification Code' => 'Код защиты от спама',
    'View' => 'Просмотр',
    'Visible' => '',
    'Websites development' => 'Создание сайтов',
    'frontend' => '',
    'hours ago' => 'часов назад',
    'in Russian / English' => 'По Русски / English',
    'one hour ago' => 'один час назад',
    'wrote' => 'написал',
    'yesterday' => 'вчера',
    'Node can not be deleted.' => 'Узел не может быть удален.',
    'Node has not parent.' => 'Узел не имеет родителя.',
    'Add' => 'Добавить',
    'Content' => 'Содержание',
];
