#!/usr/bin/env php
<?php
// run migrations
echo shell_exec('php yii migrate --migrationPath=@vendor/notgosu/yii2-meta-tag-module/src/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-byone-uploader/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-lookup/src/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-user/src/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-blog-tools/src/migrations');
// source folder
$src = './vendor/sergmoro1/yii2-blog-tools/src/temp';

echo 'Copy backend\config\params.php';
// backend/config
copy($src . '/backend/config/params.php', './backend/config/params.php');

echo 'Delete no needed files in backend\views';
// delete no needed files
if(is_file('./backend/views/site/login.php'))
    unlink('./backend/views/site/login.php');

echo 'Copy common models';
// common/models
copyFiles($src, '/common/models/');

echo 'Copy RBAC';
// console/controllers
copy($src . '/console/controllers/RbacController.php', './console/controllers/RbacController.php');
// console/rbac
if(!is_dir('./console/rbac'))
    mkdir('./console/rbac');
copyFiles($src, '/console/rbac/');

echo 'Make folders for storage uploaded files';
// frontend/web/files
if(!is_dir('./frontend/web/files'))
    mkdir('./frontend/web/files');
// make folders for files & photos
makeFolders('./frontend/web/files/', ['common', 'post', 'author', 'user']);

echo 'Make frontend\config\params.php writable to have ability change params from backend panel.';
// make frontend params writable
chmod('./frontend/config/params.php', 0777);


/**
 * Copy all files from $source$dest/ to .$dest/
 */
function copyFiles($src, $dest) {
    $path = $src . $dest;
    foreach(array_slice(scandir($path), 2) as $file)
        copy($src . $dest . $file, '.' . $dest . $file);
}
/**
 * Make subfolders in a dir
 */
function makeFolders($dir, $folders) {
    foreach($folders as $folder) {
        if(!is_dir($dir . $folder))
            mkdir($dir . $folder);
    }
}
