#!/usr/bin/env php
<?php
// run migrations
echo shell_exec('php yii migrate --migrationPath=@vendor/notgosu/yii2-meta-tag-module/src/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-byone-uploader/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-lookup/src/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-user/src/migrations');
echo shell_exec('php yii migrate --migrationPath=@vendor/sergmoro1/yii2-blog-tools/src/migrations');
